export type InputType =
    | "package.json"
    | "package-lock.json"
    | "yarn.lock"
    | "pnpm-lock.yaml"
    | "unknown";

export function detectInputType(raw: string): InputType {
    const trimmed = raw.trim();
    if (trimmed.startsWith("{")) {
        try {
            const parsed = JSON.parse(trimmed);
            if (parsed && typeof parsed === "object") {
                if ("lockfileVersion" in parsed || "packages" in parsed) {
                    return "package-lock.json";
                }
                if (
                    "dependencies" in parsed ||
                    "devDependencies" in parsed ||
                    "peerDependencies" in parsed ||
                    "optionalDependencies" in parsed
                ) {
                    return "package.json";
                }
            }
        } catch {
            return "unknown";
        }
    }
    if (
        /^#\s+THIS FILE IS GENERATED BY YARN/m.test(trimmed) ||
        /^# yarn lockfile v1/m.test(trimmed)
    ) {
        return "yarn.lock";
    }
    if (/^__metadata:/m.test(trimmed)) {
        return "yarn.lock";
    }
    if (/^lockfileVersion:/m.test(trimmed)) {
        return "pnpm-lock.yaml";
    }
    return "unknown";
}
